add acceptance tests for privacy enhancements (#66)
* Tests with privacy enhancements disabled - by default
* Tests with privacy enhancement enabled
* Tests with network upgrades
* Make network provisioning more configurable by introducing additional TF variables

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -110,6 +110,15 @@ jobs:
           - 'migration && networks/template::raft-4nodes'
           - 'migration && networks/template::istanbul-4nodes'
           - 'permissions && networks/template::raft-3plus1'
+          - 'privacy-enhancements-upgrade || networks/template::raft-4nodes-pe'
+          - 'privacy-enhancements-upgrade || networks/template::istanbul-4nodes-pe'
+        privacy-enhancements:
+          - 'false'
+        include:
+          - tag: '(basic && !privacy-enhancements-disabled) || privacy-enhancements || basic-raft || (advanced && raft) || networks/typical::raft'
+            privacy-enhancements: 'true'
+          - tag: '(basic && !privacy-enhancements-disabled) || privacy-enhancements || basic-istanbul || (advanced && istanbul) || networks/typical::istanbul'
+            privacy-enhancements: 'true'
     runs-on: ubuntu-latest
     steps:
       - name: 'Download docker image'
@@ -143,12 +152,20 @@ jobs:
           docker run \
               --name acctests-run ${{ steps.setup.outputs.dockerEnv }} \
               -v ${{ steps.setup.outputs.outputDir }}:${{ steps.setup.outputs.outputDir }} \
+              -e TF_VAR_privacy_enhancements='{ block = 0, enabled = ${{ matrix.privacy-enhancements }} }' \
               ${{ needs.docker-build.outputs.image_name }} test \
                 -PgaugeFailSafe \
                 -Pauto \
                 -Dtags="${{ matrix.tag }}" ${{ steps.setup.outputs.mvnArg }} \
                 -Dauto.outputDir=${{ steps.setup.outputs.outputDir }} \
                 -Dauto.jobid=${{ steps.setup.outputs.tag }}
+      - name: 'Failure info'
+        if: ${{ failure() }}
+        run: |
+            echo "acceptance tests failures"
+            docker images
+            docker ps -a
+            for containerId in $(docker ps -qa); do echo "container: $containerId"; docker container inspect $containerId; docker container logs $containerId; done
       - name: 'Read test report'
         if: always()
         run: |
